apiVersion: v1
kind: Secret
metadata:
  name: neilpitts-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJibVZwYkhCcGRIUnpPbmRYV21KbVJpOHdlRkZVVFZabVVGRlZibmN3TDAxYWRsQlBaSEZ5T1dodWQyZzVNbmcxTW5CbFQzTXdOVVlyZWxSTFpWTldNSEppUlZwblREaEliV2c9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson